<?php echo $this->doctype(); ?>
<html>
    <head>
        <title>GInIEm - <?php echo $this->translate('Generic'); ?></title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">

        <!-- Bootstrap -->
        <link href="/vendor/bootstrap-2.3.2/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/vendor/bootstrap-2.3.2/css/bootstrap-responsive.min.css" rel="stylesheet" />

        <?php echo $this->headLink() ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div class="navbar">
            <div class="navbar-inner">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <!-- Be sure to leave the brand out there if you want it shown -->
                <a class="brand">GInIEm Generic</a>

                <!-- Everything you want hidden at 940px or less, place within here -->
                <div class="nav-collapse collapse">
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-user"></i>&nbsp;<?php echo $this->translate('User'); ?>&nbsp;<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">  
                                <li><a id="logout" href="/auth/logout"><?php echo $this->translate('Logout') ?></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <?php echo $this->content; ?>
    </div>

    <!-- JQuery -->
    <script src="/vendor/jquery-2.0.2/jquery-2.0.2.min.js"></script>
    <!-- Bootstrap -->
    <script src="/vendor/bootstrap-2.3.2/js/bootstrap.min.js"></script>

    <?php echo $this->inlineScript(); ?>
</body>
</html>